#!/bin/bash

#SBATCH --job-name=timeArrangements
#SBATCH --output=job%A/%a.out
#SBATCH --cpus-per-task=4
#SBATCH --time=24:00:00
#SBATCH --mem=8G
#SBATCH --partition=scavenge
#SBATCH --array=0-2
#SBATCH --mail-type=BEGIN,FAIL,END

ALGOS=(
    # "annealingFromGrouped"
    # "annealingFromRandom"
    # # "linearSwitchFromGrouped"
    # # "linearSwitchFromGroupedProtected"
    # # "linearSwitchFromRandom"
    # "randomSwitchFromGrouped"
    # "randomSwitchFromRandom"
    # "tabuSearchFromGrouped"
    # "tabuSearchFromRandom"

    "bruteForce"
    "theoreticalMax"
    "theoreticalMaxTable"
)

ALGO=${ALGOS[$SLURM_ARRAY_TASK_ID]}
echo "Task $SLURM_ARRAY_TASK_ID running algorithm: $ALGO"

hostname
whoami
echo $PWD

srun apptainer run container.sif --output "job${SLURM_ARRAY_JOB_ID}" --algo "$ALGO"
