#!/bin/bash

#SBATCH --job-name=seatingTest        # Job name
#SBATCH --output=job.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=1        # Schedule one core
#SBATCH --time=00:10:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=scavenge
#SBATCH --mail-type=END          #SBATCH --mail-type=FAIL,END

# Print out the hostname of the node the job is running on
hostname
whoami
echo $PWD
python3 /home/nsio/bahcelorProject/gurobi/calc_v2.py
