#!/bin/bash

#SBATCH --job-name=seating        # Job name
#SBATCH --output=job.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=8        # Schedule one core
#SBATCH --time=24:00:00          # Run time (hh:mm:ss)
#SBATCH --mem=32G
#SBATCH --partition=dgpu
#SBATCH --mail-type=BEGIN,FAIL,END          #SBATCH --mail-type=FAIL,END

hostname
whoami
echo $PWD
srun apptainer run container.sif