#!/bin/bash

#SBATCH --job-name=seating        # Job name
#SBATCH --output=job.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=8        # Schedule one core
#SBATCH --time=24:00:00          # Run time (hh:mm:ss)
#SBATCH --mem=32G
#SBATCH --partition=scavenge
# #SBATCH --gres=gpu:rtx2070:1 
# #SBATCH --constraint="desktop"
#SBATCH --mail-type=BEGIN,FAIL,END          #SBATCH --mail-type=FAIL,END

# Print out the hostname of the node the job is running on
hostname
whoami
echo $PWD
# python3 /home/nsio/bachelorProject/gurobi/calc_v2.py
srun apptainer run container21.sif
