#!/bin/bash

#SBATCH --job-name=seating        # Job name
#SBATCH --output=job.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=90        # Schedule one core
#SBATCH --time=24:00:00          # Run time (hh:mm:ss)
#SBATCH --mem=1400G
#SBATCH --partition=scavenge
#SBATCH --mail-type=BEGIN,FAIL,END          #SBATCH --mail-type=FAIL,END

# Print out the hostname of the node the job is running on
hostname
whoami
echo $PWD
# python3 /home/nsio/bachelorProject/gurobi/calc_v2.py
srun apptainer exec container5.sif python ../gurobi/calc_v2.py --time-limit 82800 --threads 96
